In [2]:
import numpy as np
import pandas as pd

1) Check if all elements from the following arrays return the logical value True:

In [2]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 
D = np.array([0.1, 0.3])

In [4]:
for name, array in zip(list('ABCD'),[A,B,C,D]):
    print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


2) Check if all elements from the following arrays return the logical value True along the axis with index 1:

In [2]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [3]:
  
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


3) Check if any element of the following arrays returns the logical value True:

In [4]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [5]:
for name, array in zip(list('ABCD'), [A,B,C,D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


4) Check if any element of the following arrays returns the logical value True along the axis with index 0:

In [6]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [8]:
for name, array in zip(list('ABCD'), [A,B,C,D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


5. Check if the following array has missing data (np.nan):

In [9]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [10]:
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


6) Check if the following arrays are equal (element-wise):

In [11]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

In [12]:
print(np.allclose(A,B))

True


7. Check if the following arrays are equal (element-wise):

In [13]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

In [14]:
print(A==B)

[False False  True]


8) Check which numbers (element-wise) from the A array are greater than numbers from the B array and print result to the console as shown below.

In [15]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

In [16]:
print(A>B)

[ True False False False]


9. Using Numpy create a 4x4 array filled with zeros (set data type to int). In response print this array to the console.

In [18]:
array = np.zeros((4,4), dtype='int')
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


10. Using Numpy, create an array 10x10 filled with number 255 and set the data type to float. Print this array to the console as shown below.


In [21]:
array = np.ones((10,10))*255.0
print(array)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


11. Using Numpy create a one-dimensional array of all two-digit numbers and print this array to the console as shown below.

In [26]:
print(np.arange(10,100,1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


12. Using Numpy create the following array:

In [ ]:
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

In [28]:
print(np.arange(10,100).reshape((9,10)))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


13. Using Numpy create a 6x6 two-dimensional array - identity matrix with int data type. Print this array to the console as shown below.

In [ ]:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

In [29]:
print(np.eye(6,6,dtype='int'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


14. Set the random seed to 10. Then using Numpy create a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution [0,1). Print result to the console as shown below.

In [31]:
np.random.seed(10)
print(np.random.rand(30))


[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


15. Using Numpy create a two-dimensional array with the shape (10, 4) pseudo-randomly generated values from the standard normal distribution N(0,1). Set the random seed to 20. Print result to the console as shown below.

In [33]:
np.random.seed(20)
print(np.random.rand(10,4))

[[0.5881308  0.89771373 0.89153073 0.81583748]
 [0.03588959 0.69175758 0.37868094 0.51851095]
 [0.65795147 0.19385022 0.2723164  0.71860593]
 [0.78300361 0.85032764 0.77524489 0.03666431]
 [0.11669374 0.7512807  0.23921822 0.25480601]
 [0.85762553 0.94977903 0.56168686 0.17878052]
 [0.77025193 0.49238104 0.63125307 0.83949792]
 [0.4610394  0.49794007 0.67941112 0.65078591]
 [0.26879524 0.06732467 0.77144514 0.48098413]
 [0.32920641 0.51064106 0.26362883 0.31051155]]


16. Using Numpy create a two-dimensional array with the shape (10, 4) pseudo-randomly generated values from the normal distribution N(100, 5). Set the random seed to 30. Print result to the console as shown below.

In [36]:
np.random.rand(30)
sigma=np.sqrt(5)
mu=100
print(np.random.randn(10,4)*sigma+mu)

[[100.26994306 100.92578826 103.05559969  96.95174745]
 [100.03500265 102.02288173  98.19571431  98.42064204]
 [102.3543379   99.79099185  96.78240878  99.30398156]
 [101.80153119  99.97193525  99.41678224  98.01106732]
 [ 96.38673952  98.09494923  99.9079184   99.39553067]
 [ 96.63700335 102.93812139  99.93263598 101.41993241]
 [101.12347933 102.59823477  99.31632604 103.82878066]
 [102.61494062  99.38325919  94.38348759  99.06695186]
 [101.21099282  99.67553021  97.71567157 101.05604565]
 [ 98.41658771 103.16211201  98.90313451 102.64117836]]


17. The following array is given:
Iterate through this array and print each element to the console.

In [37]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])

In [38]:
[print(i) for  i in np.nditer(A)]

1
4
3
5
2
6


[None, None, None, None, None, None]

18. Using Numpy create a one-dimensional array (vector) consisting of eleven equally distributed numbers from the [0,1] interval.

In [40]:
print(np.linspace(0,1,11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


19. Using Numpy create a one-dimensional array (vector) containing the possible result from the Big Lotto game. Set the random seed to 42. Print result to the console.

Tip: The result of this game is a 6-element vector of values from 1 to 49 inclusive.

In [41]:
np.random.seed(42)
print(np.random.choice(range(1,50), size=6, replace=False))

[14 46 48 45 18 28]


20. Using Numpy create the following two-dimensional array:

In [ ]:
[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]

In [42]:
print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


21. Using Numpy create the following array. Save this array to a binary file named 'array.npy' and then load that file back into another variable. Print this variable to the console.

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
array = np.arange(0,12,1).reshape(3,4)
np.save('array.npy', array)
array2=np.load('array.npy')
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


22. Using Numpy create the following array. Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console.


In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
A=np.arange(0,12).reshape(3,4)
np.savetxt('array.txt',array)
B=np.loadtxt('array.txt')
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


23. Using Numpy create and convert the following array into the list. In response, print list to the console.

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
array = np.arange(0,12)
l = array.tolist()
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


24. Using the slice operator, transform this array into the following:

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [55]:
array=np.arange(0,12).reshape(3,4)
print(array[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


25. The following array:

In [ ]:
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

transform to this array:

In [ ]:
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [57]:
array=np.ones((4,4))
print(np.pad(array, pad_width=1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


26. The following array:

In [ ]:
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

transform to the following:

In [ ]:
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

In [58]:
array=np.zeros((6,6))
array[::2,::2] = 10
array[1::2,1::2] = 5
print(array)

[[10.  0. 10.  0. 10.  0.]
 [ 0.  5.  0.  5.  0.  5.]
 [10.  0. 10.  0. 10.  0.]
 [ 0.  5.  0.  5.  0.  5.]
 [10.  0. 10.  0. 10.  0.]
 [ 0.  5.  0.  5.  0.  5.]]


27. Combine the following arrays into one as shown below and print it to the console.

In [59]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

In [63]:
print(np.append(A,B, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


28. Extract the same elements (intersection) of the arrays as a list and print result to the console.

In [64]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      


In [65]:
print(np.intersect1d(A, B))

[0 2 3]


29. Extract all unique values of this array as a list and print it to the console.


In [66]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

In [67]:
print(np.unique(A))

[1 2 4 5 7 9]


30. Return a list of indexes with maximum values for each row from this array and print it to the console.

In [71]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])


In [72]:
print(np.argmax(A, axis=1))

[0 2 1]


31. Sort this array:
by row (ascending)
by column (ascending)
And print result to the console as shown below.

In [74]:
A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)

In [78]:
print(np.sort(A))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


32. Extract all elements from the following array with a value greater than 8 and print result to the console.


In [79]:
A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)

In [80]:
print(A[A>8])

[ 9.99  9.99 14.99]


33. Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.

In [81]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [83]:
print(np.where(A>10.0, 10.0, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


34. Present the following two-dimensional array as a flattened one-dimensional array and print result to the console.


In [84]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [85]:
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


35. Using Numpy create an array of the same shape and data type as the given array and fill it with zeros. Print this array to the console.


In [86]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [89]:
print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


36. Using Numpy create an array of the same shape and data type as the given array and fill it with a constant value = 9.99. Print this array to the console.

In [90]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [91]:
print(np.full_like(A, 9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


37. Using Numpy create a two-dimensional array (lower triangular matrix):

In [ ]:
array(
    [
        [1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]
    ]
)

In [92]:
print(np.tri(5, 5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


38. Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.

In [ ]:
[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]
 
 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]

In [94]:
A = np.arange(0,24).reshape((2,3,4))
print(A)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


39. Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.

In [96]:
print(np.random.randint(low=0, high=256, size=(200,300), dtype=np.uint8))

[[249 167 170 ... 188 154   3]
 [138  20 194 ...  38  45  74]
 [242 108 221 ... 184  57 105]
 ...
 [180  55 112 ... 143 189 122]
 [ 21  11 118 ... 244 248 221]
 [219  87 125 ... 245 135 179]]


40. Sort this array along the rows in ascending order and assign to the variable image_sorted.


In [97]:
image = np.random.randint(
    low=0, high=256, size=(200, 300), dtype=np.uint8
)

In [101]:
image_sorted = np.sort(image)
print(image_sorted)

[[  0   1   2 ... 254 254 255]
 [  0   0   0 ... 254 255 255]
 [  1   2   2 ... 254 255 255]
 ...
 [  3   3   4 ... 253 255 255]
 [  0   1   5 ... 255 255 255]
 [  0   1   2 ... 253 254 254]]


41. Expand this array by one dimension (add a new dimension at the beginning). Expected shape of the output array: (1, 2, 3).
In response, print array to the console.

In [102]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])


In [103]:
A=np.expand_dims(A,0)
print(A)

[[[4 2 1]
  [6 4 2]]]


42. Using Numpy create a three-dimensional array called image with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type np.uint8. Set random seed to 42.
In response, print array to the console.

In [104]:
np.random.seed(42)
print(np.random.randint(0,256,(200,300,3),np.uint8))

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


43. Extend this array by one dimension (add a new dimension at the beginning) and assign to image_extended variable. Expected shape of this array is (1, 200, 300, 3).

In [105]:
image = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

In [106]:
print(np.expand_dims(image, 0))

[[[[145  30 244]
   [107   6 122]
   [201  42  86]
   ...
   [182 113 173]
   [140 196 105]
   [123  60 198]]

  [[221  40 190]
   [175  36 108]
   [ 33   0 106]
   ...
   [ 75 169  71]
   [218 180 159]
   [ 88  16   4]]

  [[141 115 148]
   [211  17 146]
   [118 201  37]
   ...
   [ 10 168 141]
   [136 119 180]
   [134 202  48]]

  ...

  [[105 148  18]
   [178 143 146]
   [249 136  32]
   ...
   [ 80  45 210]
   [182 138  93]
   [ 93 176 230]]

  [[  8  92  85]
   [105 188  47]
   [188 219 100]
   ...
   [117 202 126]
   [171 254  58]
   [ 60 227 231]]

  [[ 90  77 134]
   [121 220 235]
   [ 64 117 152]
   ...
   [ 60 122  47]
   [110 218 233]
   [233  85  89]]]]


44. Expand each of these arrays by adding one dimension at the beginning and then combine these arrays into one called images. Expected shape of images array: (2, 200, 300, 3).


In [107]:
image1 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image2 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

In [109]:
image1=np.expand_dims(image1, 0)
image2=np.expand_dims(image2,0)
image=np.append(image1, image2, axis=0)
print(image)

[[[[[ 41 115 118]
    [ 84 233 122]
    [  9 233 198]
    ...
    [ 37  99 209]
    [211 120 126]
    [ 59  79  35]]

   [[136 156 232]
    [107 217 177]
    [129 224  85]
    ...
    [132  46 214]
    [107 200 163]
    [121  45 198]]

   [[ 58  69 203]
    [ 20  13 211]
    [254 145  72]
    ...
    [  6 183 128]
    [159 139  20]
    [217 117  31]]

   ...

   [[178  96 176]
    [178 151  78]
    [175 147 177]
    ...
    [169 200  37]
    [  9 171  29]
    [145 143  28]]

   [[189 185 126]
    [ 59  76 205]
    [  9 136  25]
    ...
    [ 62  31 235]
    [104 133 186]
    [154  50 165]]

   [[157 209 251]
    [181 230  48]
    [ 21 223 136]
    ...
    [ 76  88 111]
    [211 188  36]
    [ 23 111 239]]]]



 [[[[ 81  84 180]
    [239 195  87]
    [ 10 247 246]
    ...
    [ 49 136  91]
    [136 192 105]
    [  4 122 161]]

   [[121 115 195]
    [ 18   3 184]
    [253 169 244]
    ...
    [ 92 136 206]
    [ 89  89 113]
    [184   1  81]]

   [[198 236  19]
    [210  50 104]
    [ 12

45. Shape of this array is (1, 2, 3). Remove the unnecessary first dimension and extract (2, 3) array and print it to the console as shown below.

In [112]:
A = np.array([[[1, 2, 3], [6, 3, 2]]])

In [111]:
A=np.squeeze(A, 0)
print(A[0][1:])

[2 3]


46. Shape of this array is (4, 1). Remove the unnecessary dimension and extract (4, ) array and print result to the console.

In [114]:
A = np.array([[0.4], [0.9], [0.5], [0.6]])

In [117]:
A=np.squeeze(A,1)
print(A)

[0.4 0.9 0.5 0.6]


47. The following array is given:

In [118]:
A  = np.arange(12, dtype='int').reshape(-1, 4)

Using the slice operator, transform this array into the following:

In [ ]:
array(
    [
        [ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]
    ]


In [123]:
print(A[:,::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


48. Using the slice operator, transform this array into the following:


In [ ]:
array(
    [
        [11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]
    ]
)

In [124]:
A = np.arange(12, dtype='int').reshape(-1, 4)

In [128]:
print(A[::-1,::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


49. Random seed is set to 42. The following array is given:Extract the first channel (index 0) of this image array and print it to the console.


In [129]:
np.random.seed(42)

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

In [134]:
print(image[0,:,:])

[[102 220 225]
 [ 95 179  61]
 [234 203  92]
 [  3  98 243]
 [ 14 149 245]
 [ 46 106 244]
 [ 99 187  71]
 [212 153 199]
 [188 174  65]
 [153  20  44]]


50. Extract any array of shape (5, 5, 3) from this array and assign to the result variable.


In [135]:
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)


In [136]:
result = image[:5,:5,:]
print(image)

[[[129 219  27]
  [ 59  83 229]
  [ 41 175  91]
  [216 179  61]
  [110 213 173]
  [112 187  91]
  [234 174 198]
  [229  61  31]
  [171 189  40]
  [156 252 233]]

 [[195 126   7]
  [ 67  76 213]
  [174 175 205]
  [  8  34 160]
  [ 97  44 205]
  [ 56 201 232]
  [ 80 140  28]
  [100 163 103]
  [ 63  66  49]
  [  6 167  46]]

 [[103  15 155]
  [169 131  93]
  [ 95 193   1]
  [ 76 204  79]
  [253   3 215]
  [108 133  45]
  [ 35 133  53]
  [170  59  53]
  [105  52 245]
  [139   3 207]]

 [[ 84 145  53]
  [159  82  47]
  [220  37   4]
  [  8 190 178]
  [ 54 248 145]
  [249 159 215]
  [217  26 111]
  [198  43  22]
  [ 35 115 161]
  [  0 131 240]]

 [[201 144  40]
  [101 189 103]
  [ 19 229 227]
  [131  57 237]
  [ 13 249  15]
  [153  94 127]
  [ 46 186  47]
  [243 255 235]
  [ 14  45 152]
  [ 83 199 113]]

 [[167  22 205]
  [157   8 146]
  [214 238  43]
  [ 50 251 100]
  [ 85 133 248]
  [  3 148  11]
  [189  94  15]
  [246  39 217]
  [ 72  83 212]
  [ 94  51 216]]

 [[207  90 128]
  [ 99 236  

51. Concatenate these arrays as follows:




array(
    [
        [3, 4, 5],
        [8, 3, 1],
        [0, 5, 2],
        [4, 2, 1]   
    ]
)

In [3]:
A = np.array([[3, 4, 5], [8, 3, 1]])
B = np.array([[0, 5, 2], [4, 2, 1]])

In [6]:
print(np.concatenate((A,B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


52. Concatenate these arrays into one as shown below:

In [ ]:
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

In [7]:
data = np.array([[4.3, 4.2], [3.1, 3.6]])
target = np.array([[0], [1]])

In [9]:
print(np.concatenate((data, target), axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


53. Transform each of these arrays into a column and concatenate them into one array as shown below. In response, print this array to the console.

In [10]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

In [13]:
print(np.column_stack((feature1, feature2, feature3)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


54. Split this array into three parts:

the first two columns assign to the A1 variable

the next four columns assign to the A2 variable

the last two columns assign to the A3 variable

In response, print these arrays to the console as shown below

In [14]:
np.random.seed(42)

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

In [15]:
A

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])

In [17]:
A1, A2, A3 = np.split(A, [2,6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


55.Calculate the total number of non-zero elements in this array and print it to the console.

In [20]:
np.random.seed(42)
A = np.random.randint(low=0, high=2, size=(10, 6))

In [21]:
print(np.count_nonzero(A))

31


56. Set the Numpy option to print arrays with specified precision. Set precision to 4 and print this array.

In [22]:
np.random.seed(42)

A = np.random.randn(10, 4)

In [23]:
np.set_printoptions(precision=4)
print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


57. Set the precision to 8 and also set the appropriate Numpy option to suppress mathematical notation and print this array to the console.

In [24]:
A = np.array([1.2e-6, 1.7e-7])

In [26]:
np.set_printoptions(precision=8, suppress=True)
print(A)

[0.0000012  0.00000017]


58. Remove the third column and print this array to the console.

In [33]:
np.random.seed(42)

A = np.random.randn(8, 4)


In [32]:
A=np.delete(A, [2], axis=1)
print(A)

[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]


59. Calculate the norm of this vector and print result to the console.

In [34]:
v = np.array([3, 4, -2])

In [35]:
print(np.linalg.norm(v))

5.385164807134504


60. Set the Numpy option to print only ten edge elements and then print this array to the console.

In [37]:
np.random.seed(42)
A = np.random.randint(10, size=(100, 30))

In [39]:
np.set_printoptions(edgeitems=10)
print(A)

[[6 3 7 4 6 9 2 6 7 4 ... 4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3 ... 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 ... 6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7 ... 0 2 4 2 0 4 9 6 6 8]
 [9 9 2 6 0 3 3 4 6 6 ... 9 6 8 6 0 0 8 8 3 8]
 [2 6 5 7 8 4 0 2 9 7 ... 2 0 4 0 7 0 0 1 1 5]
 [6 4 0 0 2 1 4 9 5 6 ... 5 0 8 5 2 3 3 2 9 2]
 [2 3 6 3 8 0 7 6 1 7 ... 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 ... 1 1 5 2 8 3 0 3 0 4]
 [3 7 7 6 2 0 0 2 5 6 ... 4 2 3 2 0 0 4 5 2 8]
 ...
 [6 4 8 2 0 3 8 3 1 9 ... 8 4 7 1 5 2 9 4 7 9]
 [0 4 2 3 1 8 2 1 9 8 ... 7 7 6 5 8 3 0 7 6 6]
 [2 3 9 8 5 4 2 8 4 4 ... 6 1 7 5 3 4 7 2 2 3]
 [0 8 7 7 9 5 6 5 8 2 ... 2 3 7 5 4 3 7 0 8 0]
 [7 3 8 4 2 8 8 3 3 7 ... 4 4 3 4 2 0 4 8 8 3]
 [2 0 1 7 0 7 6 7 5 8 ... 2 3 6 6 3 5 2 5 1 7]
 [1 6 8 0 7 6 5 5 5 8 ... 2 7 2 3 7 0 5 0 0 7]
 [3 0 9 6 4 4 0 9 5 8 ... 6 8 6 2 0 7 2 7 7 4]
 [0 9 6 9 4 7 8 6 6 0 ... 7 3 0 0 9 2 8 6 1 8]
 [9 1 2 9 1 2 5 8 8 6 ... 8 2 0 6 9 4 4 0 8 6]]


61. Calculate arithmetic means of these arrays (elementwise) and print result to the console.


In [40]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

In [43]:
print((A+B)/2)

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


62. Multiply these arrays (elementwise) and print result to the console.

In [44]:
print(A*B)

[[12 12 18 10]
 [30  9  2 30]]


63. Calculate the square root of each element of this array and print result to the console.

In [45]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])

In [46]:
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


64. Check the Pythagorean formula for sines and cosines on the A array and then compare the result with the B array. Use the np.allclose() function in this exercise.
In response, print result to the console.

In [47]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

In [49]:
print(np.allclose(np.sin(A)**2+np.cos(A)**2, B))

True


65. Perform matrix multiplication A x B and print result to the console.


In [50]:
A = np.array([[2, 3], [-4, 2], [5, 0]])
B = np.array([[4, 3, 2], [-1, 0, 2]])


In [51]:
print(np.dot(A,B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


66. Calculate the determinant of this matrix and print it to the console.

In [52]:
A = np.array([[-2, 0, 4], [5, 2, -1], [-4, 2, 4]])

In [53]:
print(np.linalg.det(A))

51.999999999999986


67. Calculate eigenvalues and their corresponding eigenvectors of this matrix and print to the console as shown below.

In [54]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

In [56]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-0.62616472 -0.89442719  0.89015941]
 [-0.31308236 -0.          0.4450797 ]
 [ 0.71407086  0.4472136  -0.09757197]]


68. Find the inverse matrix to this matrix and print it to the console.

In [57]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

In [58]:
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


69. Find the trace of this matrix (sum of elements on the main diagonal) and print result to the console.

In [59]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

In [60]:
print(np.trace(A))

-5


70. Transform B array to perform the matrix multiplication A x B. Then perform this multiplication and print result to the console.

In [61]:
A = np.array([[2, 0], [4, 2], [5, 3], [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])


In [63]:
B=B.reshape(2,4)
print(np.matmul(A,B))

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]


71. Starting with the second row of this array, randomly shuffle the rows and print result to the console.

In [67]:
np.random.seed(42)

A = np.array(
    [
        ['id', 'price'],
        ['001', 14.99],
        ['002', 4.99],
        ['003', 7.99],
        ['004', 2.49],
        ['005', 1.49],
    ]
)

In [68]:
np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['005' '1.49']
 ['003' '7.99']
 ['001' '14.99']
 ['004' '2.49']]


72. Return a list of indexes that sorts this array in ascending order and print it to the console.

In [69]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

In [70]:
print(np.argsort(A))

[5 2 1 0 4 3]


73. Round the values of this array to three decimal places and print result to the console.

In [71]:
np.random.seed(42)
A = np.random.randn(10, 8)

In [73]:
print(np.round(A,3))

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]


74. Calculate  the roots of the following polynomial:

W(x) = 4x^^2 + 5x +1

In response, print these roots to the console.

In [74]:
W=np.array([4,5,1])
print(np.roots(W))

[-1.   -0.25]


75. Calculate the roots of the following polynomials:

Q(x) = 2x^^3 + 4x^^2 -5x +1

R(X) = 2x^^3 -5x + 1

In response print these roots to the console as shown below.

In [75]:
Q = np.array([2,4,-5,1])
R = np.array([2,-5,1])
print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[2.28077641 0.21922359]


76. The following polynomials are given:

W(x) = 4x2 + 5x + 1 Q(x) = 2x3 + 4x2 – 5x+1

Perform the following operations and print results to the console as shown below:

W(x)+Q(x) 

W(x) - Q(x) 

W(x)* Q(x) 

W(x)+2Q(x)

In [3]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])
 
print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


77.Use the sign function for this array.

Reminder: The sign function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values.

In [4]:
A = np.array([[-4, 3, 0, 1, -5], [6, -4, -2, 1, 3]])

In [5]:
print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]


78. Using the np.arange() function, generate the following array:

In [ ]:
[
    '2021-01-01'
    '2021-01-02'
    '2021-01-03'
    '2021-01-04'
    '2021-01-05'
    '2021-01-06'
    '2021-01-07'
    '2021-01-08'
    '2021-01-09'
    '2021-01-10'
    '2021-01-11'
    '2021-01-12'
    '2021-01-13'
    '2021-01-14'
    '2021-01-15'
    '2021-01-16'
    '2021-01-17'
    '2021-01-18'
    '2021-01-19'
    '2021-01-20'
    '2021-01-21'
    '2021-01-22'
    '2021-01-23'
    '2021-01-24'
    '2021-01-25'
    '2021-01-26'
    '2021-01-27'
    '2021-01-28'
    '2021-01-29'
    '2021-01-30'
    '2021-01-31'
]


In [6]:
print(np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]'))

['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']


79. Using the np.arange() function, generate the following array:

In [ ]:
array(
    [
        ['2021-01', '2021-02', '2021-03'],
        ['2021-04', '2021-05', '2021-06'],
        ['2021-07', '2021-08', '2021-09'],
        ['2021-10', '2021-11', '2021-12'],
    ],
    dtype='datetime64[M]',
)

In [8]:
print(np.arange('2021-01','2022-01',dtype='datetime64[M]'))

['2021-01' '2021-02' '2021-03' '2021-04' '2021-05' '2021-06' '2021-07'
 '2021-08' '2021-09' '2021-10' '2021-11' '2021-12']


80. Using the np.datetime64() function, generate today's date and print result to the console.

In [10]:
print(np.datetime64('today'))

2023-08-14


81. Using Numpy generate all dates for Mondays from January and February 2020 as an array and print result to the console.


In [12]:
print(np.arange('2020-01-06', '2020-02-29', dtype='datetime64[D]')[::7])

['2020-01-06' '2020-01-13' '2020-01-20' '2020-01-27' '2020-02-03'
 '2020-02-10' '2020-02-17' '2020-02-24']


82. Merge them together as shown below and print result to the console.

Tip: Use the np.char.add() function.

Expected result:

['001XC' '002YC' '003ZC']

In [13]:
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)

/var/folders/5d/chn1j4p16gb99snr1ns8vph80000gn/T/ipykernel_47997/786917039.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['001', '002', '003'], dtype=np.str)
/var/folders/5d/chn1j4p16gb99snr1ns8vph80000gn/T/ipykernel_47997/786917039.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)


In [15]:
print(np.char.add(A,B))

['001XC' '002YC' '003ZC']


83. Add '000' (3 zeros) at the beginning of each element of this array as shown below and print result to the console.


In [16]:
A = np.array(['1', '2', '3'], dtype=np.str)

/var/folders/5d/chn1j4p16gb99snr1ns8vph80000gn/T/ipykernel_47997/2401916571.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['1', '2', '3'], dtype=np.str)


In [18]:
print(np.char.zfill(A, 4))

['0001' '0002' '0003']


84. Split each element of this array by space character


In [19]:
A = np.array(
    [['PLW CDR 11B TEN', 'AMC LPP'], ['CDR PKO KGH', 'CCC QMK']],
    dtype=np.str,
)


/var/folders/5d/chn1j4p16gb99snr1ns8vph80000gn/T/ipykernel_47997/244976331.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str,


In [20]:
print(np.char.split(A, " "))

[[list(['PLW', 'CDR', '11B', 'TEN']) list(['AMC', 'LPP'])]
 [list(['CDR', 'PKO', 'KGH']) list(['CCC', 'QMK'])]]


85. Replace all # characters with spaces and then strip all unnecessary white characters around the text as shown below. In response, print this array to the console.

In [21]:
A = np.array([['#summer#time#mood'], ['#sport#time']])

In [23]:
print(np.char.strip(np.char.replace(A, '#', ' ')))

[['summer time mood']
 ['sport time']]


86. Count the number of occurrences of the word 'time' in each element of this array.


In [24]:
A = np.array(
    [
        ['#summer#time#mood', '#vibe'],
        ['#sport#time', '#good#time'],
        ['#event#summer', '#fast#move'],
    ]
)

In [26]:
print(np.char.count(A,'time'))

[[1 0]
 [1 1]
 [0 0]]


87. Instrument | ISIN code | Package | Package (PLN) | Share in portfolio (%) | Share in trading shares and PDAs per session (%) | Average spread per session

Split text into lines. Then split each line by the tab character \t and create an array (without headers) containing the following data as shown below. Assign this array to the result variable and print it to the console.

In [27]:
text = """ALIOR    PLALIOR00045    88 860 000    1 386 216 000    0,891    2,16    14
CCC    PLCCC0000016    27 918 000    1 292 603 400    0,831    5,28    42
CDPROJEKT    PLOPTTC00011    67 348 000    22 864 646 000    14,702    7,39    7
CYFRPLSAT    PLCFRPT00013    275 301 000    6 854 994 900    4,408    1,17    14
DINOPL    PLDINPL00011    47 937 000    8 916 282 000    5,733    9,13    12
JSW    PLJSW0000015    52 636 000    716 902 320    0,461    1,51    24
KGHM    PLKGHM000017    136 410 000    9 881 540 400    6,354    4,78    8
LOTOS    PLLOTOS00025    86 543 000    5 609 717 260    3,607    2,91    16
LPP    PLLPP0000011    1 306 000    7 444 200 000    4,787    1,43    19
MBANK    PLBRE0000012    12 997 000    2 830 746 600    1,820    0,42    24
ORANGEPL    PLTLKPL00017    647 357 000    4 285 503 340    2,756    1,16    13
PEKAO    PLPEKAO00016    176 379 000    9 619 710 660    6,185    5,27    9
PGE    PLPGER000010    796 776 000    3 561 588 720    2,290    2,88    18
PGNIG    PLPGNIG00014    1 624 608 000    6 072 784 704    3,905    1,56    12
PKNORLEN    PLPKN0000018    289 049 000    17 701 360 760    11,382    12,44    8
PKOBP    PLPKO0000016    857 593 000    18 807 014 490    12,093    10,49    9
PLAY    LU1642887738    114 151 000    3 696 209 380    2,377    1,47    16
PZU    PLPZU0000011    568 305 000    17 515 160 100    11,262    6,64    6
SANPL    PLBZ00000044    33 207 000    5 213 499 000    3,352    1,91    18
TAURONPE    PLTAURN00011    1 043 590 000    1 252 308 000    0,805    1,21    33"""

In [28]:
lines = text.splitlines()
lines = [line.split('\t') for line in lines]
result = np.array(lines, dtype=np.str)
print(result) 

[['ALIOR    PLALIOR00045    88 860 000    1 386 216 000    0,891    2,16    14']
 ['CCC    PLCCC0000016    27 918 000    1 292 603 400    0,831    5,28    42']
 ['CDPROJEKT    PLOPTTC00011    67 348 000    22 864 646 000    14,702    7,39    7']
 ['CYFRPLSAT    PLCFRPT00013    275 301 000    6 854 994 900    4,408    1,17    14']
 ['DINOPL    PLDINPL00011    47 937 000    8 916 282 000    5,733    9,13    12']
 ['JSW    PLJSW0000015    52 636 000    716 902 320    0,461    1,51    24']
 ['KGHM    PLKGHM000017    136 410 000    9 881 540 400    6,354    4,78    8']
 ['LOTOS    PLLOTOS00025    86 543 000    5 609 717 260    3,607    2,91    16']
 ['LPP    PLLPP0000011    1 306 000    7 444 200 000    4,787    1,43    19']
 ['MBANK    PLBRE0000012    12 997 000    2 830 746 600    1,820    0,42    24']
 ['ORANGEPL    PLTLKPL00017    647 357 000    4 285 503 340    2,756    1,16    13']
 ['PEKAO    PLPEKAO00016    176 379 000    9 619 710 660    6,185    5,27    9']
 ['PGE    PLPGER000010 

/var/folders/5d/chn1j4p16gb99snr1ns8vph80000gn/T/ipykernel_47997/179272345.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  result = np.array(lines, dtype=np.str)


88. Remove all spaces in the text and replace all commas with periods. In response, print this array to the console.

In [29]:
np.set_printoptions(linewidth=150)
result = np.array(
    [
        [
            'ALIOR',
            'PLALIOR00045',
            '88 860 000',
            '1 386 216 000',
            '0,891',
            '2,16',
            '14',
        ],
        [
            'CCC',
            'PLCCC0000016',
            '27 918 000',
            '1 292 603 400',
            '0,831',
            '5,28',
            '42',
        ],
        [
            'CDPROJEKT',
            'PLOPTTC00011',
            '67 348 000',
            '22 864 646 000',
            '14,702',
            '7,39',
            '7',
        ],
        [
            'CYFRPLSAT',
            'PLCFRPT00013',
            '275 301 000',
            '6 854 994 900',
            '4,408',
            '1,17',
            '14',
        ],
        [
            'DINOPL',
            'PLDINPL00011',
            '47 937 000',
            '8 916 282 000',
            '5,733',
            '9,13',
            '12',
        ],
        [
            'JSW',
            'PLJSW0000015',
            '52 636 000',
            '716 902 320',
            '0,461',
            '1,51',
            '24',
        ],
        [
            'KGHM',
            'PLKGHM000017',
            '136 410 000',
            '9 881 540 400',
            '6,354',
            '4,78',
            '8',
        ],
        [
            'LOTOS',
            'PLLOTOS00025',
            '86 543 000',
            '5 609 717 260',
            '3,607',
            '2,91',
            '16',
        ],
        [
            'LPP',
            'PLLPP0000011',
            '1 306 000',
            '7 444 200 000',
            '4,787',
            '1,43',
            '19',
        ],
        [
            'MBANK',
            'PLBRE0000012',
            '12 997 000',
            '2 830 746 600',
            '1,820',
            '0,42',
            '24',
        ],
        [
            'ORANGEPL',
            'PLTLKPL00017',
            '647 357 000',
            '4 285 503 340',
            '2,756',
            '1,16',
            '13',
        ],
        [
            'PEKAO',
            'PLPEKAO00016',
            '176 379 000',
            '9 619 710 660',
            '6,185',
            '5,27',
            '9',
        ],
        [
            'PGE',
            'PLPGER000010',
            '796 776 000',
            '3 561 588 720',
            '2,290',
            '2,88',
            '18',
        ],
        [
            'PGNIG',
            'PLPGNIG00014',
            '1 624 608 000',
            '6 072 784 704',
            '3,905',
            '1,56',
            '12',
        ],
        [
            'PKNORLEN',
            'PLPKN0000018',
            '289 049 000',
            '17 701 360 760',
            '11,382',
            '12,44',
            '8',
        ],
        [
            'PKOBP',
            'PLPKO0000016',
            '857 593 000',
            '18 807 014 490',
            '12,093',
            '10,49',
            '9',
        ],
        [
            'PLAY',
            'LU1642887738',
            '114 151 000',
            '3 696 209 380',
            '2,377',
            '1,47',
            '16',
        ],
        [
            'PZU',
            'PLPZU0000011',
            '568 305 000',
            '17 515 160 100',
            '11,262',
            '6,64',
            '6',
        ],
        [
            'SANPL',
            'PLBZ00000044',
            '33 207 000',
            '5 213 499 000',
            '3,352',
            '1,91',
            '18',
        ],
        [
            'TAURONPE',
            'PLTAURN00011',
            '1 043 590 000',
            '1 252 308 000',
            '0,805',
            '1,21',
            '33',
        ],
    ],
    dtype='<U14',
)


In [32]:
print(np.char.replace(np.char.replace(result, ',', '.'),' ',''))

[['ALIOR' 'PLALIOR00045' '88860000' '1386216000' '0.891' '2.16' '14']
 ['CCC' 'PLCCC0000016' '27918000' '1292603400' '0.831' '5.28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67348000' '22864646000' '14.702' '7.39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275301000' '6854994900' '4.408' '1.17' '14']
 ['DINOPL' 'PLDINPL00011' '47937000' '8916282000' '5.733' '9.13' '12']
 ['JSW' 'PLJSW0000015' '52636000' '716902320' '0.461' '1.51' '24']
 ['KGHM' 'PLKGHM000017' '136410000' '9881540400' '6.354' '4.78' '8']
 ['LOTOS' 'PLLOTOS00025' '86543000' '5609717260' '3.607' '2.91' '16']
 ['LPP' 'PLLPP0000011' '1306000' '7444200000' '4.787' '1.43' '19']
 ['MBANK' 'PLBRE0000012' '12997000' '2830746600' '1.820' '0.42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647357000' '4285503340' '2.756' '1.16' '13']
 ['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 

89. Extract all rows with the company name starting with the letter 'P' and assign to the stocks_startswith_P variable. In response, print stocks_startswith_P variable to the console.

In [34]:
np.set_printoptions(linewidth=150)
result = np.array(
    [
        [
            'ALIOR',
            'PLALIOR00045',
            '88860000',
            '1386216000',
            '0.891',
            '2.16',
            '14',
        ],
        [
            'CCC',
            'PLCCC0000016',
            '27918000',
            '1292603400',
            '0.831',
            '5.28',
            '42',
        ],
        [
            'CDPROJEKT',
            'PLOPTTC00011',
            '67348000',
            '22864646000',
            '14.702',
            '7.39',
            '7',
        ],
        [
            'CYFRPLSAT',
            'PLCFRPT00013',
            '275301000',
            '6854994900',
            '4.408',
            '1.17',
            '14',
        ],
        [
            'DINOPL',
            'PLDINPL00011',
            '47937000',
            '8916282000',
            '5.733',
            '9.13',
            '12',
        ],
        [
            'JSW',
            'PLJSW0000015',
            '52636000',
            '716902320',
            '0.461',
            '1.51',
            '24',
        ],
        [
            'KGHM',
            'PLKGHM000017',
            '136410000',
            '9881540400',
            '6.354',
            '4.78',
            '8',
        ],
        [
            'LOTOS',
            'PLLOTOS00025',
            '86543000',
            '5609717260',
            '3.607',
            '2.91',
            '16',
        ],
        [
            'LPP',
            'PLLPP0000011',
            '1306000',
            '7444200000',
            '4.787',
            '1.43',
            '19',
        ],
        [
            'MBANK',
            'PLBRE0000012',
            '12997000',
            '2830746600',
            '1.820',
            '0.42',
            '24',
        ],
        [
            'ORANGEPL',
            'PLTLKPL00017',
            '647357000',
            '4285503340',
            '2.756',
            '1.16',
            '13',
        ],
        [
            'PEKAO',
            'PLPEKAO00016',
            '176379000',
            '9619710660',
            '6.185',
            '5.27',
            '9',
        ],
        [
            'PGE',
            'PLPGER000010',
            '796776000',
            '3561588720',
            '2.290',
            '2.88',
            '18',
        ],
        [
            'PGNIG',
            'PLPGNIG00014',
            '1624608000',
            '6072784704',
            '3.905',
            '1.56',
            '12',
        ],
        [
            'PKNORLEN',
            'PLPKN0000018',
            '289049000',
            '17701360760',
            '11.382',
            '12.44',
            '8',
        ],
        [
            'PKOBP',
            'PLPKO0000016',
            '857593000',
            '18807014490',
            '12.093',
            '10.49',
            '9',
        ],
        [
            'PLAY',
            'LU1642887738',
            '114151000',
            '3696209380',
            '2.377',
            '1.47',
            '16',
        ],
        [
            'PZU',
            'PLPZU0000011',
            '568305000',
            '17515160100',
            '11.262',
            '6.64',
            '6',
        ],
        [
            'SANPL',
            'PLBZ00000044',
            '33207000',
            '5213499000',
            '3.352',
            '1.91',
            '18',
        ],
        [
            'TAURONPE',
            'PLTAURN00011',
            '1043590000',
            '1252308000',
            '0.805',
            '1.21',
            '33',
        ],
    ],
    dtype='<U12',
)


In [36]:
print(np.char.startswith(result[:,0], 'P'))

[False False False False False False False False False False False  True  True  True  True  True  True  True False False]


90. Calculate the total share of companies whose name starts with the letter 'P'. Round the result to two decimal places and print it to the console.

In [37]:
stocks_startswith_P = np.array(
    [
        [
            'PEKAO',
            'PLPEKAO00016',
            '176379000',
            '9619710660',
            '6.185',
            '5.27',
            '9',
        ],
        [
            'PGE',
            'PLPGER000010',
            '796776000',
            '3561588720',
            '2.290',
            '2.88',
            '18',
        ],
        [
            'PGNIG',
            'PLPGNIG00014',
            '1624608000',
            '6072784704',
            '3.905',
            '1.56',
            '12',
        ],
        [
            'PKNORLEN',
            'PLPKN0000018',
            '289049000',
            '17701360760',
            '11.382',
            '12.44',
            '8',
        ],
        [
            'PKOBP',
            'PLPKO0000016',
            '857593000',
            '18807014490',
            '12.093',
            '10.49',
            '9',
        ],
        [
            'PLAY',
            'LU1642887738',
            '114151000',
            '3696209380',
            '2.377',
            '1.47',
            '16',
        ],
        [
            'PZU',
            'PLPZU0000011',
            '568305000',
            '17515160100',
            '11.262',
            '6.64',
            '6',
        ],
    ],
    dtype='<U12',
)

In [39]:
print(np.round(stocks_startswith_P[:,4].astype(float).sum()),2)

49.0 2


91. Create an array from this string as shown below and assign to the wig_games variable. In response, print this array to the console.

In [55]:
wig_games_raw = """Profile    Time    Course    Change    Change%    Ref.    Open    Low    High    Volume    Turn    Share
11B (11BIT)    17 kwi 17:01    391.00    +8.00    (+2.09%)    383.00    383.50    383.00    394.00    12 784    4 994 874    19.034%
CDR (CDPROJEKT)    17 kwi 17:01    339.50    +5.30    (+1.59%)    334.20    338.30    337.00    344.20    233 059    79 245 368    39.618%
CIG (CIGAMES)    17 kwi 17:03    0.742    -0.012    (-1.59%)    0.754    0.772    0.730    0.772    1 311 078    971 459    1.855%
PLW (PLAYWAY)    17 kwi 17:03    387.50    +18.00    (+4.87%)    369.50    374.00    373.00    388.00    33 206    12 661 786    10.638%
TEN (TSGAMES)    17 kwi 17:02    349.50    +22.50    (+6.88%)    327.00    332.00    330.00    353.50    39 793    13 697 060    28.855%"""

In [56]:
lines = wig_games_raw.splitlines()
lines = [line.split('\t') for line in lines]
wig_games = np.array(lines, dtype=np.str_)
wig_games = np.char.replace(wig_games, ' ', '')
print(wig_games)

[['ProfileTimeCourseChangeChange%Ref.OpenLowHighVolumeTurnShare']
 ['11B(11BIT)17kwi17:01391.00+8.00(+2.09%)383.00383.50383.00394.0012784499487419.034%']
 ['CDR(CDPROJEKT)17kwi17:01339.50+5.30(+1.59%)334.20338.30337.00344.202330597924536839.618%']
 ['CIG(CIGAMES)17kwi17:030.742-0.012(-1.59%)0.7540.7720.7300.77213110789714591.855%']
 ['PLW(PLAYWAY)17kwi17:03387.50+18.00(+4.87%)369.50374.00373.00388.00332061266178610.638%']
 ['TEN(TSGAMES)17kwi17:02349.50+22.50(+6.88%)327.00332.00330.00353.50397931369706028.855%']]


92. Remove the following columns:

'Change'

'Change%'

'Ref.'

'Volume'

In response, print transformed array to the console.

In [57]:
np.set_printoptions(linewidth=160, suppress=True)

wig_games = np.array(
    [
        [
            'Profile',
            'Time',
            'Course',
            'Change',
            'Change%',
            'Ref.',
            'Open',
            'Low',
            'High',
            'Volume',
            'Turn',
            'Share',
        ],
        [
            '11B(11BIT)',
            '17kwi17:01',
            '391.00',
            '+8.00',
            '(+2.09%)',
            '383.00',
            '383.50',
            '383.00',
            '394.00',
            '12784',
            '4994874',
            '19.034%',
        ],
        [
            'CDR(CDPROJEKT)',
            '17kwi17:01',
            '339.50',
            '+5.30',
            '(+1.59%)',
            '334.20',
            '338.30',
            '337.00',
            '344.20',
            '233059',
            '79245368',
            '39.618%',
        ],
        [
            'CIG(CIGAMES)',
            '17kwi17:03',
            '0.742',
            '-0.012',
            '(-1.59%)',
            '0.754',
            '0.772',
            '0.730',
            '0.772',
            '1311078',
            '971459',
            '1.855%',
        ],
        [
            'PLW(PLAYWAY)',
            '17kwi17:03',
            '387.50',
            '+18.00',
            '(+4.87%)',
            '369.50',
            '374.00',
            '373.00',
            '388.00',
            '33206',
            '12661786',
            '10.638%',
        ],
        [
            'TEN(TSGAMES)',
            '17kwi17:02',
            '349.50',
            '+22.50',
            '(+6.88%)',
            '327.00',
            '332.00',
            '330.00',
            '353.50',
            '39793',
            '13697060',
            '28.855%',
        ],
    ],
    dtype='<U14',
)

In [59]:
print(np.delete(wig_games, [3,4,5,9], axis=1))

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


93. Save this array to the 'wig_games.csv' file. Then load the content of this file into the wig_games_new variable and print it to the console.

In [60]:
wig_games = np.array(
    [
        [
            'Profile',
            'Time',
            'Course',
            'Open',
            'Low',
            'High',
            'Turn',
            'Share',
        ],
        [
            '11B(11BIT)',
            '17kwi17:01',
            '391.00',
            '383.50',
            '383.00',
            '394.00',
            '4994874',
            '19.034%',
        ],
        [
            'CDR(CDPROJEKT)',
            '17kwi17:01',
            '339.50',
            '338.30',
            '337.00',
            '344.20',
            '79245368',
            '39.618%',
        ],
        [
            'CIG(CIGAMES)',
            '17kwi17:03',
            '0.742',
            '0.772',
            '0.730',
            '0.772',
            '971459',
            '1.855%',
        ],
        [
            'PLW(PLAYWAY)',
            '17kwi17:03',
            '387.50',
            '374.00',
            '373.00',
            '388.00',
            '12661786',
            '10.638%',
        ],
        [
            'TEN(TSGAMES)',
            '17kwi17:02',
            '349.50',
            '332.00',
            '330.00',
            '353.50',
            '13697060',
            '28.855%',
        ],
    ],
    dtype='<U14',
)

In [61]:
np.savetxt(fname='wig_games.csv', X = wig_games,fmt='%s', delimiter=',')
wig_games_new = np.loadtxt(fname='wig_games.csv', delimiter=',', dtype=str)
print(wig_games_new)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


94. The following string is given (Playway's March 2020 listings): 

Create an array from this string as shown below and assign to the playway variable. In response, print this array to the console.

In [62]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""


In [63]:
lines = playway_raw.splitlines()
lines = [line.split(',') for line in lines]
playway = np.array(lines, dtype=np.str_)
print(playway)

[['Date' 'Open' 'High' 'Low' 'Close' 'Volume']
 ['2020-03-02' '305' '324.5' '283.5' '310' '64081']
 ['2020-03-03' '325.5' '340.5' '320' '340.5' '55496']
 ['2020-03-04' '324' '340.5' '315' '330' '36152']
 ['2020-03-05' '344' '344' '310' '315' '35992']
 ['2020-03-06' '306.5' '307' '291' '305' '32539']
 ['2020-03-09' '274' '291' '250' '258' '79402']
 ['2020-03-10' '278' '284.5' '256' '264' '35700']
 ['2020-03-11' '270' '270' '238.5' '245' '60445']
 ['2020-03-12' '218' '228' '196' '197' '94031']
 ['2020-03-13' '210' '229' '198.8' '211' '100412']
 ['2020-03-16' '205' '248' '197.8' '240.5' '50659']
 ['2020-03-17' '245' '269' '232.5' '264' '99480']
 ['2020-03-18' '264' '280' '251' '270' '70136']
 ['2020-03-19' '267' '280' '267' '279.5' '30732']
 ['2020-03-20' '297.5' '307' '280' '280.5' '43426']
 ['2020-03-23' '274' '289' '258' '285' '37098']
 ['2020-03-24' '305' '309' '296.5' '309' '31939']
 ['2020-03-25' '313' '330' '295' '304' '46724']
 ['2020-03-26' '300' '309' '295.5' '300' '27213']
 ['2

95. Delete the 'Date' column. Then remove the headers and assign result to the playway_values variable. Convert this array to the float data type and print result to the console.

In [66]:
playway = np.array(
    [
        ['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
        ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
        ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
        ['2020-03-04', '324', '340.5', '315', '330', '36152'],
        ['2020-03-05', '344', '344', '310', '315', '35992'],
        ['2020-03-06', '306.5', '307', '291', '305', '32539'],
        ['2020-03-09', '274', '291', '250', '258', '79402'],
        ['2020-03-10', '278', '284.5', '256', '264', '35700'],
        ['2020-03-11', '270', '270', '238.5', '245', '60445'],
        ['2020-03-12', '218', '228', '196', '197', '94031'],
        ['2020-03-13', '210', '229', '198.8', '211', '100412'],
        ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
        ['2020-03-17', '245', '269', '232.5', '264', '99480'],
        ['2020-03-18', '264', '280', '251', '270', '70136'],
        ['2020-03-19', '267', '280', '267', '279.5', '30732'],
        ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
        ['2020-03-23', '274', '289', '258', '285', '37098'],
        ['2020-03-24', '305', '309', '296.5', '309', '31939'],
        ['2020-03-25', '313', '330', '295', '304', '46724'],
        ['2020-03-26', '300', '309', '295.5', '300', '27213'],
        ['2020-03-27', '302', '306.5', '290', '296', '13466'],
        ['2020-03-30', '299', '300', '287', '300', '10316'],
        ['2020-03-31', '302.5', '309', '302', '306.5', '15698'],
    ],
    dtype='<U10',
)

In [67]:
playway = np.delete(playway, [0], axis=1)
playway_values = playway[1:].astype(float)
print(playway_values)

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

96. Calculate the average value for each column. Round the result to two decimal places and print it to the console.

In [68]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)


In [70]:
print(np.mean(playway_values, axis=0))

[  283.13636364   295.25         268.68636364   282.29545455 48688.04545455]


97. Calculate the new column: the difference between the highest and lowest price.

Steps:

Assign the calculated difference to the max_min_diff variable

Add the calculated column (variable max_min_diff) to the array playway_values at the end.

In response, print result to the console.

In [71]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)


In [72]:
max_min_diff = playway_values[:, [1]] - playway_values[:, [2]]
playway_values = np.concatenate((playway_values, max_min_diff), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

98. Extract rows from this array where closing price (column with index 3) is greater than 300.0. In response, print result to the console.

In [76]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

In [78]:
print(playway_values[playway_values[:,3]>300.0])

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


99. From this array extract the first 10 rows with the highest volume sorted in descending order.

In [79]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)


In [83]:
print(playway_values[playway_values[:,4].argsort()][::-1][:10])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


100. Add to this array column that returns 1 in case the close price is higher than the open price, otherwise 0.

In [82]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

In [86]:
flag = playway_values[:,[0]] < playway_values[:,[3]]
flag = flag.astype(int)
playway_values = np.concatenate((playway_values, flag), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 

In [87]:
flag

array([[1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1]])