In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2


## PyTorch Fundamentals

In [5]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [6]:
#Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# Tensor 
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [25]:

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1462, 0.0479, 0.3658, 0.1650],
        [0.4133, 0.3498, 0.1116, 0.8648],
        [0.0521, 0.6142, 0.2583, 0.6025]])

In [29]:

random_tensor.ndim

3

In [30]:
random_image_Size_tensor = torch.rand(size=(3,244,244))
random_image_Size_tensor

tensor([[[0.7029, 0.1990, 0.0161,  ..., 0.6535, 0.1638, 0.9071],
         [0.1943, 0.9584, 0.5282,  ..., 0.7245, 0.7945, 0.4944],
         [0.5516, 0.5036, 0.4166,  ..., 0.0198, 0.6636, 0.0783],
         ...,
         [0.6857, 0.5626, 0.2485,  ..., 0.3797, 0.5967, 0.5278],
         [0.4510, 0.6940, 0.4536,  ..., 0.9463, 0.6372, 0.5980],
         [0.3019, 0.0118, 0.8610,  ..., 0.3512, 0.9671, 0.7672]],

        [[0.4409, 0.4331, 0.4618,  ..., 0.2329, 0.4883, 0.9439],
         [0.1984, 0.0176, 0.7934,  ..., 0.8153, 0.8807, 0.5104],
         [0.5541, 0.9534, 0.2627,  ..., 0.4765, 0.6515, 0.9692],
         ...,
         [0.8424, 0.8959, 0.6918,  ..., 0.7227, 0.5583, 0.1294],
         [0.5659, 0.2872, 0.7553,  ..., 0.5160, 0.0597, 0.3448],
         [0.1062, 0.9826, 0.7437,  ..., 0.2522, 0.6492, 0.2377]],

        [[0.3562, 0.2239, 0.8924,  ..., 0.5348, 0.3147, 0.7079],
         [0.2163, 0.5004, 0.1994,  ..., 0.0171, 0.0813, 0.9733],
         [0.1979, 0.9782, 0.9689,  ..., 0.3565, 0.7250, 0.

### Zeros and Ones  

In [31]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
one.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [38]:

one_to_ten = torch.arange(0,10)

In [39]:
# tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [41]:
float32_tensor = torch.tensor([3.0,6.0,9.0], 
                              dtype=None,
                              device='cpu',
                              requires_grad=False)
float32_tensor.dtype

torch.float32

In [42]:
float_16_tensor = float32_tensor.type(torch.half)
float_16_tensor.dtype

torch.float16

In [43]:
float32_tensor*float32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensors

In [44]:
tensor = torch.tensor([1,2,3])
tensor + 10 

tensor([11, 12, 13])

In [45]:
tensor*10

tensor([10, 20, 30])

In [46]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [49]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [50]:
#Multiplying matrices   
tensor * tensor

tensor([1, 4, 9])

In [51]:
torch.matmul(tensor, tensor)

tensor(14)

In [54]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.6542, 1.0494, 1.0125],
        [0.3920, 0.4395, 0.4619],
        [0.6389, 1.0498, 1.0079]])

In [56]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [58]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
torch.max(x), x.min()

(tensor(90), tensor(0))

In [62]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [63]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [64]:
x.argmin()

tensor(0)

### Reshaping, Stacking, Squeezing and unsqueezing tensors

In [65]:
x = torch.arange(1.0,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# Add extra dimension   
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.size

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), <function Tensor.size>)

In [71]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [79]:
#Squeeze
x = torch.zeros(2,1,2,1,2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [86]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [81]:
y = torch.squeeze(x,1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [89]:
y.unsqueeze(dim=1)
y.size()

torch.Size([2, 2, 2])

In [94]:
#permute
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape


torch.Size([224, 224, 3])

In [93]:
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing

In [96]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [97]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
x[0][0]

tensor([1, 2, 3])

In [99]:
x[0][0][0]

tensor(1)

In [101]:
# Get all elements of 0th and 1st dimension but only index 1 of 2nd dimension. 
x[:,:,1]

tensor([[2, 5, 8]])

In [102]:
# Get all elements of 0th  dimension but only index 1 of 1st and 2nd dimension. 
x[:,1,1]


tensor([5])

In [103]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension. 
x[0,0,:]


tensor([1, 2, 3])

In [105]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [106]:
# Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

### PyTorch vs Numpy

In [108]:
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

### Reproducibility

In [113]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_A = torch.arange(3,4)
random_tensor_B = torch.arange(3,4)
print(random_tensor_A==random_tensor_B)

tensor([True])


In [114]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu
